name: gtk-theme-matcha
build-base: core24
base: bare
version: '2025-06-09'
platforms:
  all:
    build-on: [amd64]
    build-for: [all]
summary: Matcha GTK theme
description: |
  A Snap that allows you to use Matcha GTK themes in Snap apps
grade: stable
confinement: strict

slots:
  gtk-2-themes:
    interface: content
    source:
      read:
        - $SNAP/share/gtk2/Matcha-aliz
        - $SNAP/share/gtk2/Matcha-azul
        - $SNAP/share/gtk2/Matcha-dark-aliz
        - $SNAP/share/gtk2/Matcha-dark-azul
        - $SNAP/share/gtk2/Matcha-dark-pueril
        - $SNAP/share/gtk2/Matcha-dark-sea
        - $SNAP/share/gtk2/Matcha-light-aliz
        - $SNAP/share/gtk2/Matcha-light-azul
        - $SNAP/share/gtk2/Matcha-light-pueril
        - $SNAP/share/gtk2/Matcha-light-sea
        - $SNAP/share/gtk2/Matcha-pueril
        - $SNAP/share/gtk2/Matcha-sea
  gtk-3-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/Matcha-aliz
        - $SNAP/share/themes/Matcha-azul
        - $SNAP/share/themes/Matcha-dark-aliz
        - $SNAP/share/themes/Matcha-dark-azul
        - $SNAP/share/themes/Matcha-dark-pueril
        - $SNAP/share/themes/Matcha-dark-sea
        - $SNAP/share/themes/Matcha-light-aliz
        - $SNAP/share/themes/Matcha-light-azul
        - $SNAP/share/themes/Matcha-light-pueril
        - $SNAP/share/themes/Matcha-light-sea
        - $SNAP/share/themes/Matcha-pueril
        - $SNAP/share/themes/Matcha-sea
parts:
  gtk-2-themes:
    plugin: dump
    source: https://github.com/Kyuyrii/gtk-theme-matcha-snap/releases/download/gtk-theme-matcha/gtk-theme-matcha-snap-creation-files_2025-06-09.deb
    organize:
      usr/share/themes: share/gtk2
    prime:
      - share/gtk2/*/gtk-2.0
  gtk-3-themes:
    plugin: dump
    source: https://github.com/Kyuyrii/gtk-theme-matcha-snap/releases/download/gtk-theme-matcha/gtk-theme-matcha-snap-creation-files_2025-06-09.deb
    organize:
      usr/share/themes: share/themes
    prime:
      - share/themes/*/gtk-3.0
      - share/themes/*/gtk-4.0
